# Generated by Django 5.1.4 on 2024-12-21 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='订单编号')),
                ('status', models.IntegerField(choices=[(0, '待付款'), (1, '已付款'), (2, '已取消')], default=0, verbose_name='订单状态')),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='订单备注')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单列表',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='支付记录ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='支付流水号')),
                ('payment_method', models.IntegerField(choices=[(0, '微信支付'), (1, '支付宝')], verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('payment_status', models.IntegerField(choices=[(0, '处理中'), (1, '成功'), (2, '失败')], default=0, verbose_name='支付状态')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付网关交易号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录列表',
                'db_table': 'payment',
            },
        ),
    ]
