services:
  mysql:
    image: mysql:8
    container_name: mysql-8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r2EM5VgS^pMkMnTevmAciasXbPHiwX6  # 设置 root 用户密码
      MYSQL_DATABASE: redirect            # 设置默认数据库
      MYSQL_USER: redirect              # 设置自定义用户
      MYSQL_PASSWORD: r2EM5VgS^pMkMnTevmAciasXbPHiwX6  # 设置自定义用户密码
    ports:
      - "3306:3306"                        # 映射端口
    volumes:
      - ./mysql_data:/var/lib/mysql          # 数据持久化

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # 将本地的6379端口映射到容器的6379端口
    volumes:
      - ./redis_data:/data # 持久化 Redis 数据
    command: ["redis-server", "--appendonly", "yes"] # 启用持久化
    restart: always

